#! /bin/bash

# Get PIA user/pass
USERNAME=`head -n 1 /etc/openvpn/pw`
PASSWORD=`head -n 2 /etc/openvpn/pw | tail -1`
DEVICE=tun0
CLIENTID=`cat /etc/openvpn/mvad_client`
MVAD_PORT=`cat /etc/openvpn/mvad_port`

# Get tun ip address
LOCAL_IP=`ip -o addr show $DEVICE | awk '$3 == "inet" {split($4,i,"/"); print i[1]; exit}'`

# Get the port number for the forwarded port
#PORT=`curl -s -d "user=$USERNAME&pass=$PASSWORD&client_id=$CLIENTID&local_ip=$LOCAL_IP" https://www.privateinternetaccess.com/vpninfo/port_forward_assignment | head -1 | grep -Po "[0-9]*"`
#with mullvad we get a port. don't know what the API is yet
[ -z "${MVAD_PORT}" ] && echo "[crit] MVAD_PORT not specified" && exit 1

if [[ $MVAD_PORT =~ ^-?[0-9]+$ ]] 
then
  echo [set-deluge-port] Local IP=$LOCAL_IP, Port=$MVAD_PORT, Client ID=$CLIENTID
  deluge-console -c /app/deluge "config --set random_port False"
  deluge-console -c /app/deluge "config --set listen_ports ($MVAD_PORT,$MVAD_PORT)"
  deluge-console -c /app/deluge "config --set listen_interface $LOCAL_IP"
else
  echo ERROR: Port $MVAD_PORT is not an integer
  exit 1
fi

exit 0

